//다중 선택 가능
final Set<String> multiSelectFields = {'season'};

//공통: 선택지
final Map<String, List<String>> fixedOptions = {
  'style1': [
    'casual',
    'street',
    'gorpcore',
    'workwear',
    'preppy',
    'sporty',
    'romantic',
    'girlish',
    'classic',
    'minimal',
    'chic',
    'retro',
    'ethnic',
    'resort',
    'balletcore',
  ],
  'style2': [
    'casual',
    'street',
    'gorpcore',
    'workwear',
    'preppy',
    'sporty',
    'romantic',
    'girlish',
    'classic',
    'minimal',
    'chic',
    'retro',
    'ethnic',
    'resort',
    'balletcore',
  ],
  'style3': [
    'casual',
    'street',
    'gorpcore',
    'workwear',
    'preppy',
    'sporty',
    'romantic',
    'girlish',
    'classic',
    'minimal',
    'chic',
    'retro',
    'ethnic',
    'resort',
    'balletcore',
  ],
  'color': [
    'red',
    'orange',
    'yellow',
    'light green',
    'green',
    'blue green',
    'blue',
    'navy',
    'purple',
    'red purple',
    'achromatic',
    'pink',
  ],
  'saturation': ['high', 'medium', 'low', 'achromatic'],
  'brightness': ['white', 'high', 'medium', 'low', 'black'],
  'pattern': [
    'stripe',
    'check',
    'flower',
    'dot',
    'patchwork',
    'camouflage',
    'paisley',
    'tropical',
    'hound tooth',
    'herringbone',
    'other pattern',
    'plain',
  ],
  'season': ['spring', 'summer', 'autumn', 'winter'],
};
//타입별: 선택지
final Map<String, Map<String, List<String>>> typeSpecificOptions = {
  'top': {
    'category': [
      'sweatshirt',
      'hooded sweatshirt',
      'shirt/blouse',
      't-shirt',
      'knit',
    ],
    'topLength': ['half', 'crop', 'regular', 'long'],
    'sleeveLength': [
      'sleeveless',
      'short sleeves',
      'three-quarter sleeves',
      'long sleeves',
    ],
    'fit': ['slim', 'regular', 'oversize'],
  },
  'pants': {
    'category': [
      'denim pants',
      'training pants',
      'cotton pants',
      'suit pants/slack',
      'leggings',
      'jumpsuit/overall',
    ],
    'bottomLength': [
      'shorts',
      'bermuda pants',
      'capri pants',
      'ankle pants',
      'long pants',
    ],
    'pantsFit': [
      'wide',
      'straight',
      'tapered',
      'slim/skinny',
      'boot cut',
      'baggy fit',
      'jogger fit',
    ],
  },
  'skirt': {
    'skirtLength': ['mini skirt', 'midi skirt', 'long skirt'],
    'skirtFit': ['a-line', 'h-line', 'balloon', 'pencil'],
    'skirtType': ['pleats', 'wrap', 'tiered', 'skirt pants', 'cancan', 'plain'],
  },
  'dress': {
    'skirtLength': ['mini skirt', 'midi skirt', 'long skirt'],
    'skirtFit': ['a-line', 'h-line', 'balloon', 'pencil'],
    'sleeveLength': [
      'sleeveless',
      'short sleeves',
      'three-quarter sleeves',
      'long sleeves',
    ],
    'fit': ['slim', 'regular', 'oversize'],
    'skirtType': ['pleats', 'wrap', 'tiered', 'skirt pants', 'cancan', 'plain'],
  },
  'outer': {
    'category': [
      'hooded zip-up',
      'blouson/MA-1',
      'leather/riders jacket',
      'cardigan',
      'trucker jacket',
      'suit/blazer jacket',
      'stadium jacket',
      'nylon/coach jacket',
      'anorak jacket',
      'training jacket',
      'season change coat',
      'safari/hunting jacket',
      'padding',
      'mustang/fur',
      'fleece',
      'winter coat',
      'tweed jacket',
    ],
    'topLength': ['half', 'crop', 'regular', 'long'],
    'sleeveLength': [
      'sleeveless',
      'short sleeves',
      'three-quarter sleeves',
      'long sleeves',
    ],
    'fit': ['slim', 'regular', 'oversize'],
  },
};
//공통: 줄글
final List<String> fixedTextFields = ['tpo', 'detail1', 'detail2', 'detail3'];
//타입별: 줄글
final Map<String, List<String>> typeSpecificTextFields = {
  'top': ['print'],
};
//타입별: true,false
final Map<String, List<String>> typeSpecificBooleanFields = {
  'top': ['isSeeThrough', 'isSimple'],
  'dress': ['isTopRequired', 'isSeeThrough'],
  'outer': ['isSeeThrough'],
};

/* 타입 별 필드 */
const Map<String, List<String>> fieldsByType = {
  'top': [
    'imageUrl',
    'season',
    'style1',
    'style2',
    'style3',
    'color',
    'saturation',
    'brightness',
    'pattern',
    'category',
    'topLength',
    'sleeveLength',
    'fit',
    'tpo',
    'detail1',
    'detail2',
    'detail3',
    'print',
    'isSeeThrough',
    'isSimple',
  ],
  'pants': [
    'imageUrl',
    'season',
    'style1',
    'style2',
    'style3',
    'color',
    'saturation',
    'brightness',
    'pattern',
    'category',
    'bottomLength',
    'pantsFit',
    'tpo',
    'detail1',
    'detail2',
    'detail3',
  ],
  'skirt': [
    'imageUrl',
    'season',
    'style1',
    'style2',
    'style3',
    'color',
    'saturation',
    'brightness',
    'pattern',
    'category',
    'skirtLength',
    'skirtFit',
    'skirtType',
    'tpo',
    'detail1',
    'detail2',
    'detail3',
  ],
  'dress': [
    'imageUrl',
    'season',
    'style1',
    'style2',
    'style3',
    'color',
    'saturation',
    'brightness',
    'pattern',
    'category',
    'skirtLength',
    'skirtFit',
    'skirtType',
    'sleeveLength',
    'tpo',
    'detail1',
    'detail2',
    'detail3',
    'isSeeThrough',
    'isTopRequired',
  ],
  'outer': [
    'imageUrl',
    'season',
    'style1',
    'style2',
    'style3',
    'color',
    'saturation',
    'brightness',
    'pattern',
    'category',
    'topLength',
    'sleeveLength',
    'fit',
    'tpo',
    'detail1',
    'detail2',
    'detail3',
    'print',
    'isSeeThrough',
  ],
};

/*필드 이름 변환*/
const Map<String, String> fieldLabels = {
  'season': '계절',
  'style1': '스타일1',
  'style2': '스타일2',
  'style3': '스타일3',
  'color': '색상',
  'saturation': '채도',
  'brightness': '명도',
  'pattern': '패턴',
  'category': '카테고리',
  'topLength': '상의 길이',
  'sleeveLength': '소매 길이',
  'fit': '핏',
  'bottomLength': '하의 길이',
  'pantsFit': '바지 핏',
  'skirtLength': '치마 길이',
  'skirtFit': '치마 핏',
  'skirtType': '치마 종류',
  'tpo': 'TPO',
  'detail1': '디테일1',
  'detail2': '디테일2',
  'detail3': '디테일3',
  'print': '프린트 설명',
  'isSeeThrough': '비침 여부',
  'isSimple': '심플 여부',
  'isTopRequired': '상의 필요 여부',
};
String labelFor(String field) => fieldLabels[field] ?? field;

const Map<String, Map<String, String>> categorizedLabelMapping = {
  // ✅ 스타일 필드 (style1, style2, style3에 공통 적용)
  'style1': {
    'casual': '캐주얼',
    'street': '스트리트',
    'gorpcore': '고프코어',
    'workwear': '워크웨어',
    'preppy': '프레피',
    'sporty': '스포티',
    'romantic': '로맨틱',
    'girlish': '걸리시',
    'classic': '클래식',
    'minimal': '미니멀',
    'chic': '시크',
    'retro': '레트로',
    'ethnic': '에스닉',
    'resort': '리조트',
    'balletcore': '발레코어',
  },
  'style2': {
    'casual': '캐주얼',
    'street': '스트리트',
    'gorpcore': '고프코어',
    'workwear': '워크웨어',
    'preppy': '프레피',
    'sporty': '스포티',
    'romantic': '로맨틱',
    'girlish': '걸리시',
    'classic': '클래식',
    'minimal': '미니멀',
    'chic': '시크',
    'retro': '레트로',
    'ethnic': '에스닉',
    'resort': '리조트',
    'balletcore': '발레코어',
  },
  'style3': {
    'casual': '캐주얼',
    'street': '스트리트',
    'gorpcore': '고프코어',
    'workwear': '워크웨어',
    'preppy': '프레피',
    'sporty': '스포티',
    'romantic': '로맨틱',
    'girlish': '걸리시',
    'classic': '클래식',
    'minimal': '미니멀',
    'chic': '시크',
    'retro': '레트로',
    'ethnic': '에스닉',
    'resort': '리조트',
    'balletcore': '발레코어',
  },

  // ✅ 색상 관련
  'color': {
    'red': '빨강',
    'orange': '주황',
    'yellow': '노랑',
    'light green': '연두',
    'green': '초록',
    'blue green': '청록',
    'blue': '파랑',
    'navy': '남색',
    'purple': '보라',
    'red purple': '자주',
    'achromatic': '무채색',
    'pink': '핑크',
  },
  'saturation': {
    'high': '높음',
    'medium': '중간',
    'low': '낮음',
    'achromatic': '무채색',
  },
  'brightness': {
    'white': '하양',
    'high': '밝음',
    'medium': '중간',
    'low': '어두움',
    'black': '검정',
  },

  // ✅ 패턴
  'pattern': {
    'stripe': '스트라이프',
    'check': '체크',
    'flower': '꽃무늬',
    'dot': '도트',
    'patchwork': '패치워크',
    'camouflage': '카모플라주',
    'paisley': '페이즐리',
    'tropical': '트로피컬',
    'hound tooth': '하운드투스',
    'herringbone': '헤링본',
    'other pattern': '기타 패턴',
    'plain': '무지',
  },

  // ✅ 계절
  'season': {'spring': '봄', 'summer': '여름', 'autumn': '가을', 'winter': '겨울'},

  // ✅ 상의 카테고리
  'category': {
    'sweatshirt': '맨투맨',
    'hooded sweatshirt': '후드티',
    'shirt/blouse': '셔츠/블라우스',
    't-shirt': '티셔츠',
    'knit': '니트',
    'denim pants': '데님 팬츠',
    'training pants': '트레이닝 팬츠',
    'cotton pants': '면바지',
    'suit pants/slack': '슬랙스',
    'leggings': '레깅스',
    'jumpsuit/overall': '점프수트/오버롤',
    'hooded zip-up': '후드 집업',
    'blouson/MA-1': '블루종/MA-1',
    'leather/riders jacket': '가죽/라이더 자켓',
    'cardigan': '가디건',
    'trucker jacket': '트러커 자켓',
    'suit/blazer jacket': '수트/블레이저 자켓',
    'stadium jacket': '스타디움 자켓',
    'nylon/coach jacket': '나일론/코치 자켓',
    'anorak jacket': '아노락 자켓',
    'training jacket': '트레이닝 자켓',
    'season change coat': '간절기 코트',
    'safari/hunting jacket': '사파리/헌팅 자켓',
    'padding': '패딩',
    'mustang/fur': '무스탕/퍼',
    'fleece': '플리스',
    'winter coat': '겨울 코트',
    'tweed jacket': '트위드 자켓',
  },

  // ✅ 상의/아우터 길이
  'topLength': {'half': '하프', 'crop': '크롭', 'regular': '레귤러', 'long': '롱'},

  // ✅ 소매 길이
  'sleeveLength': {
    'sleeveless': '민소매',
    'short sleeves': '반소매',
    'three-quarter sleeves': '7부 소매',
    'long sleeves': '긴소매',
  },

  // ✅ 핏
  'fit': {'slim': '슬림핏', 'regular': '레귤러핏', 'oversize': '오버핏'},

  // ✅ 바지 길이
  'bottomLength': {
    'shorts': '반바지',
    'bermuda pants': '버뮤다 팬츠',
    'capri pants': '카프리 팬츠',
    'ankle pants': '복숭아뼈 길이',
    'long pants': '긴바지',
  },

  // ✅ 바지 핏
  'pantsFit': {
    'wide': '와이드핏',
    'straight': '스트레이트핏',
    'tapered': '테이퍼드핏',
    'slim/skinny': '슬림/스키니핏',
    'boot cut': '부츠컷',
    'baggy fit': '배기핏',
    'jogger fit': '조거핏',
  },

  // ✅ 치마 길이
  'skirtLength': {
    'mini skirt': '미니스커트',
    'midi skirt': '미디스커트',
    'long skirt': '롱스커트',
  },

  // ✅ 치마 핏
  'skirtFit': {
    'a-line': 'A라인',
    'h-line': 'H라인',
    'balloon': '벌룬핏',
    'pencil': '펜슬핏',
  },

  // ✅ 치마 유형
  'skirtType': {
    'pleats': '플리츠',
    'wrap': '랩 스타일',
    'tiered': '티어드',
    'skirt pants': '치마바지',
    'cancan': '캉캉',
    'plain': '무지',
  },
};
