//다중 선택 가능
final Set<String> multiSelectFields = {'season'};

//공통: 선택지
final Map<String, List<String>> fixedOptions = {
  'style1': [
    'casual',
    'street',
    'gorpcore',
    'workwear',
    'preppy',
    'sporty',
    'romantic',
    'girlish',
    'classic',
    'minimal',
    'chic',
    'retro',
    'ethnic',
    'resort',
    'balletcore',
  ],
  'style2': [
    'casual',
    'street',
    'gorpcore',
    'workwear',
    'preppy',
    'sporty',
    'romantic',
    'girlish',
    'classic',
    'minimal',
    'chic',
    'retro',
    'ethnic',
    'resort',
    'balletcore',
  ],
  'style3': [
    'casual',
    'street',
    'gorpcore',
    'workwear',
    'preppy',
    'sporty',
    'romantic',
    'girlish',
    'classic',
    'minimal',
    'chic',
    'retro',
    'ethnic',
    'resort',
    'balletcore',
  ],
  'color': [
    'red',
    'orange',
    'yellow',
    'light green',
    'green',
    'blue green',
    'blue',
    'navy',
    'purple',
    'red purple',
    'achromatic',
    'pink',
  ],
  'saturation': ['high', 'medium', 'low', 'achromatic'],
  'brightness': ['white', 'high', 'medium', 'low', 'black'],
  'pattern': [
    'stripe',
    'check',
    'flower',
    'dot',
    'patchwork',
    'camouflage',
    'paisley',
    'tropical',
    'hound tooth',
    'herringbone',
    'other pattern',
    'plain',
  ],
  'season': ['spring', 'summer', 'autumn', 'winter'],
};
//타입별: 선택지
final Map<String, Map<String, List<String>>> typeSpecificOptions = {
  'top': {
    'category': [
      'sweatshirt',
      'hooded sweatshirt',
      'shirt/blouse',
      't-shirt',
      'knit',
    ],
    'topLength': ['half', 'crop', 'regular', 'long'],
    'sleeveLength': [
      'sleeveless',
      'short sleeves',
      'three-quarter sleeves',
      'long sleeves',
    ],
    'fit': ['slim', 'regular', 'oversize'],
  },
  'pants': {
    'category': [
      'denim pants',
      'training pants',
      'cotton pants',
      'suit pants/slack',
      'leggings',
      'jumpsuit/overall',
    ],
    'bottomLength': [
      'shorts',
      'bermuda pants',
      'capri pants',
      'ankle pants',
      'long pants',
    ],
    'pantsFit': [
      'wide',
      'straight',
      'tapered',
      'slim/skinny',
      'boot cut',
      'baggy fit',
      'jogger fit',
    ],
  },
  'skirt': {
    'skirtLength': ['mini skirt', 'midi skirt', 'long skirt'],
    'skirtFit': ['a-line', 'h-line', 'balloon', 'pencil'],
    'skirtType': ['pleats', 'wrap', 'tiered', 'skirt pants', 'cancan', 'plain'],
  },
  'dress': {
    'skirtLength': ['mini skirt', 'midi skirt', 'long skirt'],
    'skirtFit': ['a-line', 'h-line', 'balloon', 'pencil'],
    'sleeveLength': [
      'sleeveless',
      'short sleeves',
      'three-quarter sleeves',
      'long sleeves',
    ],
    'fit': ['slim', 'regular', 'oversize'],
    'skirtType': ['pleats', 'wrap', 'tiered', 'skirt pants', 'cancan', 'plain'],
  },
  'outer': {
    'category': [
      'hooded zip-up',
      'blouson/MA-1',
      'leather/riders jacket',
      'cardigan',
      'trucker jacket',
      'suit/blazer jacket',
      'stadium jacket',
      'nylon/coach jacket',
      'anorak jacket',
      'training jacket',
      'season change coat',
      'safari/hunting jacket',
      'padding',
      'mustang/fur',
      'fleece',
      'winter coat',
      'tweed jacket',
    ],
    'topLength': ['half', 'crop', 'regular', 'long'],
    'sleeveLength': [
      'sleeveless',
      'short sleeves',
      'three-quarter sleeves',
      'long sleeves',
    ],
    'fit': ['slim', 'regular', 'oversize'],
  },
};
//공통: 줄글
final List<String> fixedTextFields = ['tpo', 'detail1', 'detail2', 'detail3'];
//타입별: 줄글
final Map<String, List<String>> typeSpecificTextFields = {
  'top': ['print'],
};
//타입별: true,false
final Map<String, List<String>> typeSpecificBooleanFields = {
  'top': ['isSeeThrough', 'isSimple'],
  'dress': ['isTopRequired', 'isSeeThrough'],
  'outer': ['isSeeThrough'],
};

/* 타입 별 필드 */
const Map<String, List<String>> fieldsByType = {
  'top': [
    'imageUrl',
    'season',
    'style1',
    'style2',
    'style3',
    'color',
    'saturation',
    'brightness',
    'pattern',
    'category',
    'topLength',
    'sleeveLength',
    'fit',
    'tpo',
    'detail1',
    'detail2',
    'detail3',
    'print',
    'isSeeThrough',
    'isSimple',
  ],
  'pants': [
    'imageUrl',
    'season',
    'style1',
    'style2',
    'style3',
    'color',
    'saturation',
    'brightness',
    'pattern',
    'category',
    'bottomLength',
    'pantsFit',
    'tpo',
    'detail1',
    'detail2',
    'detail3',
  ],
  'skirt': [
    'imageUrl',
    'season',
    'style1',
    'style2',
    'style3',
    'color',
    'saturation',
    'brightness',
    'pattern',
    'category',
    'skirtLength',
    'skirtFit',
    'skirtType',
    'tpo',
    'detail1',
    'detail2',
    'detail3',
  ],
  'dress': [
    'imageUrl',
    'season',
    'style1',
    'style2',
    'style3',
    'color',
    'saturation',
    'brightness',
    'pattern',
    'category',
    'skirtLength',
    'skirtFit',
    'skirtType',
    'sleeveLength',
    'tpo',
    'detail1',
    'detail2',
    'detail3',
    'isSeeThrough',
    'isTopRequired',
  ],
  'outer': [
    'imageUrl',
    'season',
    'style1',
    'style2',
    'style3',
    'color',
    'saturation',
    'brightness',
    'pattern',
    'category',
    'topLength',
    'sleeveLength',
    'fit',
    'tpo',
    'detail1',
    'detail2',
    'detail3',
    'print',
    'isSeeThrough',
  ],
};

/*필드 이름 변환*/
const Map<String, String> fieldLabels = {
  'season': '계절',
  'style1': '스타일1',
  'style2': '스타일2',
  'style3': '스타일3',
  'color': '색상',
  'saturation': '채도',
  'brightness': '명도',
  'pattern': '패턴',
  'category': '카테고리',
  'topLength': '상의 길이',
  'sleeveLength': '소매 길이',
  'fit': '핏',
  'bottomLength': '하의 길이',
  'pantsFit': '바지 핏',
  'skirtLength': '치마 길이',
  'skirtFit': '치마 핏',
  'skirtType': '치마 종류',
  'tpo': 'TPO',
  'detail1': '디테일1',
  'detail2': '디테일2',
  'detail3': '디테일3',
  'print': '프린트 설명',
  'isSeeThrough': '비침 여부',
  'isSimple': '심플 여부',
  'isTopRequired': '상의 필요 여부',
};
String labelFor(String field) => fieldLabels[field] ?? field;
